name: Google search update
on:
  push:
    branches:
      - gh-pages
  schedule:
    - cron: '50 0 * * 5'
jobs:
  update-google-search:
    runs-on: ubuntu-latest
    steps:
      - name: Updating sitemap
        run: curl 'https://www.google.com/ping?sitemap=https%3A%2F%2Fngeojiajun.github.io%2Fsitemap.xml'
